/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tesis2herramienta;

import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import pe.edu.pucp.tesis.algorithm.Grasp;
import pe.edu.pucp.tesis.algorithm.VariablesGenericas;
import pe.edu.pucp.tesis.algorithm.Voraz;
import pe.edu.pucp.tesis.config.ConfigAlgoritmo;
import pe.edu.pucp.tesis.model.Medico;
import pe.edu.pucp.tesis.model.Paciente;
import sun.misc.Compare;

/**
 *
 * @author PC-HP
 */
public class WindowSimulacionReview extends javax.swing.JFrame {
    
    public WindowSimulacionReview(Grasp g,Voraz v, VariablesGenericas vg) {
        this.getContentPane().setBackground(Color.WHITE);
        initComponents();
        mostrarResultados(g,v,vg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtPacientesAtendidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        txtCitasSinEntregar = new javax.swing.JTextField();
        txtNumSem = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumEsp = new javax.swing.JTextField();
        txtCitasEntregadas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtFuncionObjetivoVoraz = new javax.swing.JTextField();
        E9 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultadoVoraz = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        E4 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFuncionObjetivoGrasp = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        E10 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaResultadoGRASP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        E5 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        jLabel5.setText("Número de pacientes atendidos");

        txtPacientesAtendidos.setEditable(false);
        txtPacientesAtendidos.setText("300");

        jLabel6.setText("Número de médicos");

        jTextField28.setEditable(false);
        jTextField28.setText("300");

        txtCitasSinEntregar.setEditable(false);
        txtCitasSinEntregar.setText("300");

        txtNumSem.setEditable(false);
        txtNumSem.setText("300");

        jLabel20.setText("Número de semanas de trabajo");

        jLabel9.setText("Número de citas sin entregar");

        jLabel7.setText("Número de citas entregadas");

        jLabel8.setText("Número de especialidades");

        txtNumEsp.setEditable(false);
        txtNumEsp.setText("300");
        txtNumEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumEspActionPerformed(evt);
            }
        });

        txtCitasEntregadas.setEditable(false);
        txtCitasEntregadas.setText("300");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Resultados según el modelo actual");

        jLabel12.setText("Valor función objetivo de solución");

        txtFuncionObjetivoVoraz.setEditable(false);

        E9.setName(""); // NOI18N

        tablaResultadoVoraz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><center>Paciente</center></html>", "<html><center>Medico</center></html>", "Especialidad", "<html><center>Tiempo de<br>espera</center></html>", "<html><center>Orden<br>Atención</center></html>", "Bondad Pac.", "Bondad Med.", "Beneficio aportado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaResultadoVoraz);
        if (tablaResultadoVoraz.getColumnModel().getColumnCount() > 0) {
            tablaResultadoVoraz.getColumnModel().getColumn(0).setMinWidth(100);
            tablaResultadoVoraz.getColumnModel().getColumn(0).setMaxWidth(100);
            tablaResultadoVoraz.getColumnModel().getColumn(1).setMinWidth(100);
            tablaResultadoVoraz.getColumnModel().getColumn(1).setMaxWidth(100);
            tablaResultadoVoraz.getColumnModel().getColumn(2).setMaxWidth(80);
            tablaResultadoVoraz.getColumnModel().getColumn(3).setMinWidth(60);
            tablaResultadoVoraz.getColumnModel().getColumn(3).setMaxWidth(60);
            tablaResultadoVoraz.getColumnModel().getColumn(4).setMinWidth(60);
            tablaResultadoVoraz.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        E9.addTab("General", jScrollPane1);

        jLabel4.setText("Pacientes <3 años");

        jLabel10.setText("18años < Pacientes <65 años");

        jLabel11.setText("3años < Pacientes <18 años");

        jLabel13.setText("Pacientes >65 años");

        jTextField16.setEditable(false);
        jTextField16.setText("300");

        jTextField17.setEditable(false);
        jTextField17.setText("300");

        jTextField18.setEditable(false);
        jTextField18.setText("300");

        jTextField19.setEditable(false);
        jTextField19.setText("300");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        E9.addTab("Por edad", jPanel1);

        E4.setName(""); // NOI18N
        E9.addTab("Por ingresos mensuales", E4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        E9.addTab("Por carga familiar", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        E9.addTab("Por categoría de enfermedad Dx.", jPanel5);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Resultados con optimización");

        txtFuncionObjetivoGrasp.setEditable(false);

        jLabel21.setText("Valor función objetivo de solución");

        E10.setName(""); // NOI18N

        tablaResultadoGRASP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><center>Paciente</center></html>", "<html><center>Medico</center></html>", "Especialidad", "<html><center>Tiempo de<br>espera</center></html>", "<html><center>Orden<br>Atención</center></html>", "Bondad Pac.", "Bondad Med.", "Beneficio aportado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaResultadoGRASP);
        if (tablaResultadoGRASP.getColumnModel().getColumnCount() > 0) {
            tablaResultadoGRASP.getColumnModel().getColumn(0).setMinWidth(100);
            tablaResultadoGRASP.getColumnModel().getColumn(0).setMaxWidth(100);
            tablaResultadoGRASP.getColumnModel().getColumn(1).setMinWidth(100);
            tablaResultadoGRASP.getColumnModel().getColumn(1).setMaxWidth(100);
            tablaResultadoGRASP.getColumnModel().getColumn(2).setMaxWidth(80);
            tablaResultadoGRASP.getColumnModel().getColumn(3).setMinWidth(60);
            tablaResultadoGRASP.getColumnModel().getColumn(3).setMaxWidth(60);
            tablaResultadoGRASP.getColumnModel().getColumn(4).setMinWidth(60);
            tablaResultadoGRASP.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        E10.addTab("General", jScrollPane2);

        jLabel14.setText("Pacientes <3 años");

        jLabel15.setText("18años < Pacientes <65 años");

        jLabel16.setText("3años < Pacientes <18 años");

        jLabel17.setText("Pacientes >65 años");

        jTextField20.setEditable(false);
        jTextField20.setText("300");

        jTextField21.setEditable(false);
        jTextField21.setText("300");

        jTextField22.setEditable(false);
        jTextField22.setText("300");

        jTextField23.setEditable(false);
        jTextField23.setText("300");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        E10.addTab("Por edad", jPanel2);

        E5.setName(""); // NOI18N
        E10.addTab("Por ingresos mensuales", E5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        E10.addTab("Por carga familiar", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        E10.addTab("Por categoría de enfermedad Dx.", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel20))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCitasSinEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E9, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPacientesAtendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCitasEntregadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(txtFuncionObjetivoVoraz, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(txtFuncionObjetivoGrasp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(E10, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtPacientesAtendidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCitasEntregadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCitasSinEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNumEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtNumSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(E9, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFuncionObjetivoVoraz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(txtFuncionObjetivoGrasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addComponent(E10, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumEspActionPerformed

    public void mostrarResultados(Grasp g, Voraz v,VariablesGenericas vg)
    {
        //Resultados genéricos
        txtCitasEntregadas.setText(v.pacientesAtendidos+"");
        txtCitasSinEntregar.setText((vg.numeroTotalCitas-v.pacientesAtendidos)+"");
        txtPacientesAtendidos.setText(v.pacientesAtendidos+"");
        txtNumEsp.setText(ConfigAlgoritmo.N_ESPECIALIDADES+"");
        txtNumSem.setText(ConfigAlgoritmo.N_SEMANAS_TRABAJO+"");
        
        //Resultados Voraz
        if (v!=null)
        {
        DefaultTableModel modeloVoraz=(DefaultTableModel)tablaResultadoVoraz.getModel();
        int [][] _MA_Voraz=(int[][])v.listaSol.get(0);
        int [][] _MO_Voraz=(int[][])v.listaSol.get(1);
        int [] _listaPacientesxPosMedico_Voraz=v.listaPacientesxPosMedicos;
        
           for (int p=0;p<ConfigAlgoritmo.N_PACIENTES;p++)
           {
               int indexMedicoAsignado=_listaPacientesxPosMedico_Voraz[p];
               System.out.println(p+"-"+indexMedicoAsignado);
               if (_MA_Voraz[p][indexMedicoAsignado]!=0)
               {
                   Paciente px=v.listaPacientes.get(p);
                   
                   //Creamos las filas para la tabla de resultados
                   Object[] filaVoraz=new Object[8];
                   filaVoraz[0]=px.getNombre();
                   filaVoraz[1]=v.listaMedicos.get(indexMedicoAsignado).getNombre();
                   filaVoraz[2]=v.listaMedicos.get(indexMedicoAsignado).getEspecialidad();
                   filaVoraz[3]=_MA_Voraz[px.getPosMatriz()][indexMedicoAsignado];
                   filaVoraz[4]=_MO_Voraz[px.getPosMatriz()][indexMedicoAsignado];
                   double bM=v.bondadMedicoxPaciente[px.getPosMatriz()];
                   double bP=px.getBondad();
                   filaVoraz[5]=Math.floor(bP*100)/100;
                   filaVoraz[6]=Math.floor(bM*100)/100;
                   filaVoraz[7]=(bM*bP)/(_MA_Voraz[px.getPosMatriz()][indexMedicoAsignado]);
//                   filaVoraz[5]=px.getBondad();
                   modeloVoraz.addRow(filaVoraz);
               }
           }
         
         tablaResultadoVoraz.setModel(modeloVoraz);
         System.out.println("***************** "+v.fObjetivo);
         txtFuncionObjetivoVoraz.setText((v.fObjetivo/1000)+"");
         TableRowSorter<TableModel> x=new TableRowSorter<TableModel>(modeloVoraz);
         tablaResultadoVoraz.setRowSorter(x);
        }
        //Resultados Grasp
        
        if (g!=null)
        {
        DefaultTableModel modeloGrasp=(DefaultTableModel)tablaResultadoGRASP.getModel();
        int [][] _MA_Grasp=(int[][])g.listaSol.get(0);
        int [][] _MO_Grasp=(int[][])g.listaSol.get(1);
        int [] _listaPacientesxPosMedico_Grasp=g.listaPacientesxPosMedicos;
        
           for (int p=0;p<ConfigAlgoritmo.N_PACIENTES;p++)
           {
               int indexMedicoAsignado=_listaPacientesxPosMedico_Grasp[p];
               if (_MA_Grasp[p][indexMedicoAsignado]!=0)
               {
                   Paciente px=g.listaPacientes.get(p);
                   
                   //Creamos las filas para la tabla de resultados
                   Object[] filaGrasp=new Object[8];
                   filaGrasp[0]=px.getNombre();
                   filaGrasp[1]=g.listaMedicos.get(indexMedicoAsignado).getNombre();
                   filaGrasp[2]=g.listaMedicos.get(indexMedicoAsignado).getEspecialidad();
                   filaGrasp[3]=_MA_Grasp[px.getPosMatriz()][indexMedicoAsignado];
                   filaGrasp[4]=_MO_Grasp[px.getPosMatriz()][indexMedicoAsignado];
                   double bM=g.bondadMedicoxPaciente[px.getPosMatriz()];
                   double bP=px.getBondad();
                   filaGrasp[5]=Math.floor(bP*100)/100;
                   filaGrasp[6]=Math.floor(bM*100)/100;
                   filaGrasp[7]=(bP*bM)/(_MA_Grasp[px.getPosMatriz()][indexMedicoAsignado]);
//                   filaGrasp[5]=px.getBondad();
                   modeloGrasp.addRow(filaGrasp);
               }
           }
          
         tablaResultadoGRASP.setModel(modeloGrasp);
         TableRowSorter<TableModel> y=new TableRowSorter<TableModel>(modeloGrasp);
         tablaResultadoGRASP.setRowSorter(y);
        }
         txtFuncionObjetivoGrasp.setText((g.fObjetivo/1000)+"");
         
    }
    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(WindowSimulacionReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WindowSimulacionReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WindowSimulacionReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WindowSimulacionReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WindowSimulacionReview().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane E10;
    private javax.swing.JTabbedPane E4;
    private javax.swing.JTabbedPane E5;
    private javax.swing.JTabbedPane E9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTable tablaResultadoGRASP;
    private javax.swing.JTable tablaResultadoVoraz;
    private javax.swing.JTextField txtCitasEntregadas;
    private javax.swing.JTextField txtCitasSinEntregar;
    private javax.swing.JTextField txtFuncionObjetivoGrasp;
    private javax.swing.JTextField txtFuncionObjetivoVoraz;
    private javax.swing.JTextField txtNumEsp;
    private javax.swing.JTextField txtNumSem;
    private javax.swing.JTextField txtPacientesAtendidos;
    // End of variables declaration//GEN-END:variables
}
