/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tesis2herramienta;

/**
 *
 * @author PC-HP
 */
public class WindowUsuariosPanel extends javax.swing.JPanel {

    /**
     * Creates new form WindowUsuariosPanel
     */
    public WindowUsuariosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        chkCargaDatos = new javax.swing.JCheckBox();
        chkConfigPar = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        chkUsuarios = new javax.swing.JCheckBox();
        chkSimulacion = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"admin", "Juan", "Perez", "jperez@gmail.com", "********"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Nombres", "Apellidos", "Email", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Permisos asignados");

        chkCargaDatos.setBackground(new java.awt.Color(255, 255, 255));
        chkCargaDatos.setText("Carga de datos");

        chkConfigPar.setBackground(new java.awt.Color(255, 255, 255));
        chkConfigPar.setText("<html><center>Configuración de<br>parámetros</center></html>");
        chkConfigPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkConfigParActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(194, 227, 234));
        jButton2.setText("Guardar cambios");

        chkUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        chkUsuarios.setText("Usuarios");

        chkSimulacion.setBackground(new java.awt.Color(255, 255, 255));
        chkSimulacion.setText("Simulación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCargaDatos)
                                    .addComponent(chkConfigPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkUsuarios)
                                    .addComponent(chkSimulacion)))
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkCargaDatos)
                            .addComponent(chkSimulacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkConfigPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkUsuarios))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkConfigParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkConfigParActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkConfigParActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkCargaDatos;
    private javax.swing.JCheckBox chkConfigPar;
    private javax.swing.JCheckBox chkSimulacion;
    private javax.swing.JCheckBox chkUsuarios;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
